version: "3"
services:
  node-app:
    build: .
    image: richter84/docker-node
    depends_on:
      - mongo-db
  
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  mongo-db: