version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    deploy:
      replicas: 6
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: ["npm", "start"]

  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  nginx:
    ports:
      - "80:80"